; Script generated for Inno Setup
; Builds a complete offline installer with custom drive selection, shortcuts, and uninstaller.

[Setup]
AppId={{A3D89E78-29A1-41F6-B203-8889FA111222}}
AppName=MediCare Hospital POS
AppVersion=1.0.0
AppPublisher=MediCare Systems
; Allows the user to select ANY installation drive (e.g., C:\, D:\, E:\)
DefaultDirName={autopf}\MediCarePOS
DefaultGroupName=MediCare Hospital POS
; Specifies the application icon used in Windows Add/Remove Programs
UninstallDisplayIcon={app}\app.exe
Compression=lzma2
SolidCompression=yes
OutputDir=Output
OutputBaseFilename=MediCare_POS_Setup

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; Desktop shortcut checkbox during installation (Requirement 7)
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Packages all files generated by PyInstaller from the dist/app directory
Source: "dist\app\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Creates Start Menu shortcut
Name: "{group}\MediCare POS"; Filename: "{app}\app.exe"
; Creates Desktop shortcut automatically if selected
Name: "{autodesktop}\MediCare POS"; Filename: "{app}\app.exe"; Tasks: desktopicon

[Run]
; Launches the application right after installation completes
Filename: "{app}\app.exe"; Description: "Launch MediCare POS"; Flags: postinstall nowait skipifsilent